INITIAL_CARDS = [
    {
        "type": "tap",
        "title": "When life gets noisy, what do you naturally protect?",
        "subtitle": "Choose the signal that feels most true today.",
        "options": ["My energy", "My freedom", "My progress", "My people"],
        "tags": ["values", "direction", "onboarding"],
        "signal_weights": {
            "My energy": {"body": 2, "self_awareness": 1},
            "My freedom": {"autonomy": 2, "adventure": 1},
            "My progress": {"discipline": 2, "ambition": 1},
            "My people": {"relationships": 2, "social": 1},
        },
        "is_onboarding": True,
        "visual_theme": "signal",
        "icon": "✦",
        "position": 1,
    },
    {
        "type": "this_or_that",
        "title": "Tonight, would you rather feel proud or peaceful?",
        "subtitle": "There is no correct answer. Only a direction.",
        "options": ["Proud", "Peaceful"],
        "tags": ["emotion", "alignment", "onboarding"],
        "signal_weights": {
            "Proud": {"achievement": 2, "discipline": 1},
            "Peaceful": {"recovery": 2, "balance": 1},
        },
        "is_onboarding": True,
        "visual_theme": "void",
        "icon": "☾",
        "position": 2,
    },
    {
        "type": "swipe",
        "title": "I want my days to prove something to myself.",
        "subtitle": "Swipe right if this resonates. Swipe left if not today.",
        "options": ["Resonates", "Not for me"],
        "tags": ["identity", "ambition", "onboarding"],
        "signal_weights": {
            "Resonates": {"ambition": 2, "identity": 1, "persistence": 1},
            "Not for me": {"ease": 1, "non_attachment": 1},
        },
        "is_onboarding": True,
        "visual_theme": "gold",
        "icon": "◆",
        "position": 3,
    },
    {
        "type": "tap",
        "title": "Which kind of challenge attracts you most?",
        "subtitle": "Your character learns from what pulls your attention.",
        "options": ["Build something", "Master a skill", "Move my body", "Understand myself"],
        "tags": ["growth_area", "challenge", "onboarding"],
        "signal_weights": {
            "Build something": {"builder": 2, "creativity": 1},
            "Master a skill": {"learning": 2, "discipline": 1},
            "Move my body": {"fitness": 2, "energy": 1},
            "Understand myself": {"reflection": 2, "self_awareness": 1},
        },
        "is_onboarding": True,
        "visual_theme": "ember",
        "icon": "⚒",
        "position": 4,
    },
    {
        "type": "this_or_that",
        "title": "A good day is more about direction or intensity?",
        "subtitle": "The Forge remembers patterns, not perfection.",
        "options": ["Direction", "Intensity"],
        "tags": ["forge", "pace", "onboarding"],
        "signal_weights": {
            "Direction": {"consistency": 2, "clarity": 1},
            "Intensity": {"drive": 2, "ambition": 1},
        },
        "is_onboarding": True,
        "visual_theme": "deepblue",
        "icon": "➤",
        "position": 5,
    },
    {
        "type": "swipe",
        "title": "Small promises matter more than big plans.",
        "subtitle": "Swipe right if you want the app to push tiny action first.",
        "options": ["Resonates", "Not for me"],
        "tags": ["promises", "action", "onboarding"],
        "signal_weights": {
            "Resonates": {"consistency": 2, "action": 2},
            "Not for me": {"vision": 1, "planning": 1},
        },
        "is_onboarding": True,
        "visual_theme": "pulse",
        "icon": "🔥",
        "position": 6,
    },
    {
        "type": "tap",
        "title": "What do you want JotPop to notice first?",
        "subtitle": "This final signal opens the gate.",
        "options": ["My actions", "My thoughts", "My discipline", "My direction"],
        "tags": ["jotpop", "first_path", "onboarding"],
        "signal_weights": {
            "My actions": {"action": 2, "forge": 1},
            "My thoughts": {"reflection": 2, "jot": 1},
            "My discipline": {"discipline": 2, "persistence": 1},
            "My direction": {"clarity": 2, "identity": 1},
        },
        "is_onboarding": True,
        "visual_theme": "aether",
        "icon": "◇",
        "position": 7,
    },
    {
        "type": "challenge",
        "title": "Move one unfinished thing forward by 10 minutes.",
        "subtitle": "Not completion. Just movement.",
        "options": ["Accept challenge", "Skip"],
        "tags": ["challenge", "action", "promise_seed"],
        "signal_weights": {
            "Accept challenge": {"action": 2, "discipline": 1, "forge": 1},
            "Skip": {"resistance": 1},
        },
        "is_onboarding": False,
        "visual_theme": "ember",
        "icon": "⚒",
        "position": 101,
    },
    {
        "type": "micro_jot",
        "title": "What has been quietly asking for your attention?",
        "subtitle": "Jot it down. 140 chars max.",
        "options": [],
        "tags": ["micro_jot", "reflection"],
        "signal_weights": {"submitted": {"reflection": 2, "self_awareness": 1}},
        "is_onboarding": False,
        "visual_theme": "void",
        "icon": "✍",
        "position": 102,
    },
    {
        "type": "tap",
        "title": "Which energy do you want more of tomorrow?",
        "subtitle": "Pick a direction, not a perfect plan.",
        "options": ["Calm focus", "Bold action", "Physical energy", "Creative fire"],
        "tags": ["energy", "tomorrow", "feed"],
        "signal_weights": {
            "Calm focus": {"focus": 2, "clarity": 1},
            "Bold action": {"action": 2, "courage": 1},
            "Physical energy": {"fitness": 2, "body": 1},
            "Creative fire": {"creativity": 2, "builder": 1},
        },
        "is_onboarding": False,
        "visual_theme": "pulse",
        "icon": "◉",
        "position": 103,
    },
]

# Step 29 — varied feed library.
# Replaces the repetitive Step 27 generated copy with 100 more varied cards.
# Existing Step 27 generated cards are deactivated by seed_service if they are no longer in this seed set.
VARIED_FEED_CARDS = [{'type': 'this_or_that',
  'title': 'Ship the rough version or Polish in private?',
  'subtitle': 'The rough version can teach faster than the perfect draft.',
  'options': ['Ship the rough version', 'Polish in private'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Ship the rough version': {'act': 2, 'courage': 1},
                     'Polish in private': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '◇',
  'position': 301},
 {'type': 'this_or_that',
  'title': 'Ask for the answer or Try for 20 minutes first?',
  'subtitle': 'One path seeks help. One path builds friction tolerance.',
  'options': ['Ask for the answer', 'Try for 20 minutes first'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Ask for the answer': {'act': 2, 'courage': 1},
                     'Try for 20 minutes first': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '◇',
  'position': 302},
 {'type': 'this_or_that',
  'title': 'Train the body or Train the mind?',
  'subtitle': 'Both change the character. Which one calls today?',
  'options': ['Train the body', 'Train the mind'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Train the body': {'act': 2, 'courage': 1},
                     'Train the mind': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '◇',
  'position': 303},
 {'type': 'this_or_that',
  'title': 'Be seen early or Stay hidden longer?',
  'subtitle': 'This choice reveals your relationship with visibility.',
  'options': ['Be seen early', 'Stay hidden longer'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Be seen early': {'act': 2, 'courage': 1},
                     'Stay hidden longer': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '◇',
  'position': 304},
 {'type': 'this_or_that',
  'title': 'Cut one commitment or Add one challenge?',
  'subtitle': 'Growth is sometimes subtraction, sometimes pressure.',
  'options': ['Cut one commitment', 'Add one challenge'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Cut one commitment': {'act': 2, 'courage': 1},
                     'Add one challenge': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '◇',
  'position': 305},
 {'type': 'this_or_that',
  'title': 'Work in silence or Invite feedback?',
  'subtitle': 'Choose the atmosphere that would move you now.',
  'options': ['Work in silence', 'Invite feedback'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Work in silence': {'act': 2, 'courage': 1},
                     'Invite feedback': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '◇',
  'position': 306},
 {'type': 'this_or_that',
  'title': 'Start before clarity or Wait for a cleaner plan?',
  'subtitle': 'A builder often discovers clarity by moving.',
  'options': ['Start before clarity', 'Wait for a cleaner plan'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Start before clarity': {'act': 2, 'courage': 1},
                     'Wait for a cleaner plan': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '◇',
  'position': 307},
 {'type': 'this_or_that',
  'title': 'Choose discipline or Choose recovery?',
  'subtitle': 'The useful answer depends on what you have been avoiding.',
  'options': ['Choose discipline', 'Choose recovery'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Choose discipline': {'act': 2, 'courage': 1},
                     'Choose recovery': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '◇',
  'position': 308},
 {'type': 'this_or_that',
  'title': 'Protect focus or Follow curiosity?',
  'subtitle': 'Both can be noble. Pick the truer pull.',
  'options': ['Protect focus', 'Follow curiosity'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Protect focus': {'act': 2, 'courage': 1},
                     'Follow curiosity': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '◇',
  'position': 309},
 {'type': 'this_or_that',
  'title': 'Make it simple or Make it impressive?',
  'subtitle': 'The popular path often rewards impressive. Your path may need simple.',
  'options': ['Make it simple', 'Make it impressive'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Make it simple': {'act': 2, 'courage': 1},
                     'Make it impressive': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '◇',
  'position': 310},
 {'type': 'this_or_that',
  'title': 'Do the visible thing or Do the important thing?',
  'subtitle': 'Status and progress are not always the same signal.',
  'options': ['Do the visible thing', 'Do the important thing'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Do the visible thing': {'act': 2, 'courage': 1},
                     'Do the important thing': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '◇',
  'position': 311},
 {'type': 'this_or_that',
  'title': 'Say no fast or Explore one more angle?',
  'subtitle': 'Boundaries and openness both shape the map.',
  'options': ['Say no fast', 'Explore one more angle'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Say no fast': {'act': 2, 'courage': 1},
                     'Explore one more angle': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '◇',
  'position': 312},
 {'type': 'this_or_that',
  'title': 'Repeat the boring rep or Search for novelty?',
  'subtitle': 'Mastery and exploration fight for your attention.',
  'options': ['Repeat the boring rep', 'Search for novelty'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Repeat the boring rep': {'act': 2, 'courage': 1},
                     'Search for novelty': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '◇',
  'position': 313},
 {'type': 'this_or_that',
  'title': 'Lead the conversation or Listen longer?',
  'subtitle': 'Your social pattern appears in small choices.',
  'options': ['Lead the conversation', 'Listen longer'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Lead the conversation': {'act': 2, 'courage': 1},
                     'Listen longer': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '◇',
  'position': 314},
 {'type': 'this_or_that',
  'title': 'Risk being wrong or Stay comfortably vague?',
  'subtitle': 'Precision makes identity testable.',
  'options': ['Risk being wrong', 'Stay comfortably vague'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Risk being wrong': {'act': 2, 'courage': 1},
                     'Stay comfortably vague': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '◇',
  'position': 315},
 {'type': 'this_or_that',
  'title': 'Finish one loop or Open a new door?',
  'subtitle': 'Completion and discovery both have a cost.',
  'options': ['Finish one loop', 'Open a new door'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Finish one loop': {'act': 2, 'courage': 1},
                     'Open a new door': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '◇',
  'position': 316},
 {'type': 'this_or_that',
  'title': 'Build for yourself or Build for someone specific?',
  'subtitle': 'A product changes when it has a real person in mind.',
  'options': ['Build for yourself', 'Build for someone specific'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Build for yourself': {'act': 2, 'courage': 1},
                     'Build for someone specific': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '◇',
  'position': 317},
 {'type': 'this_or_that',
  'title': 'Move now or Understand first?',
  'subtitle': 'Action and reflection need rhythm, not ideology.',
  'options': ['Move now', 'Understand first'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Move now': {'act': 2, 'courage': 1}, 'Understand first': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '◇',
  'position': 318},
 {'type': 'this_or_that',
  'title': 'Be intense or Be consistent?',
  'subtitle': 'Intensity burns bright. Consistency leaves traces.',
  'options': ['Be intense', 'Be consistent'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Be intense': {'act': 2, 'courage': 1}, 'Be consistent': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '◇',
  'position': 319},
 {'type': 'this_or_that',
  'title': 'Simplify the goal or Raise the standard?',
  'subtitle': 'Your next step may need less ambition or more honesty.',
  'options': ['Simplify the goal', 'Raise the standard'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Simplify the goal': {'act': 2, 'courage': 1},
                     'Raise the standard': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '◇',
  'position': 320},
 {'type': 'this_or_that',
  'title': 'Practice alone or Compete with others?',
  'subtitle': 'Some growth needs privacy. Some growth needs pressure.',
  'options': ['Practice alone', 'Compete with others'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Practice alone': {'act': 2, 'courage': 1},
                     'Compete with others': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '◇',
  'position': 321},
 {'type': 'this_or_that',
  'title': 'Write the thought or Do the task?',
  'subtitle': 'Jots reveal patterns. Action tests them.',
  'options': ['Write the thought', 'Do the task'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Write the thought': {'act': 2, 'courage': 1},
                     'Do the task': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '◇',
  'position': 322},
 {'type': 'this_or_that',
  'title': 'Fix the weak link or Double down on strength?',
  'subtitle': 'A good day can repair or amplify.',
  'options': ['Fix the weak link', 'Double down on strength'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Fix the weak link': {'act': 2, 'courage': 1},
                     'Double down on strength': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '◇',
  'position': 323},
 {'type': 'this_or_that',
  'title': 'Choose the uncomfortable truth or Choose the useful next step?',
  'subtitle': 'One clarifies. One moves.',
  'options': ['Choose the uncomfortable truth', 'Choose the useful next step'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Choose the uncomfortable truth': {'act': 2, 'courage': 1},
                     'Choose the useful next step': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '◇',
  'position': 324},
 {'type': 'this_or_that',
  'title': 'Spend energy or Save energy?',
  'subtitle': 'The right answer depends on tomorrow’s cost.',
  'options': ['Spend energy', 'Save energy'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Spend energy': {'act': 2, 'courage': 1}, 'Save energy': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '◇',
  'position': 325},
 {'type': 'this_or_that',
  'title': 'Become harder to distract or Become easier to inspire?',
  'subtitle': 'Focus and aliveness are different muscles.',
  'options': ['Become harder to distract', 'Become easier to inspire'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Become harder to distract': {'act': 2, 'courage': 1},
                     'Become easier to inspire': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '◇',
  'position': 326},
 {'type': 'this_or_that',
  'title': 'Follow the plan or Break the pattern?',
  'subtitle': 'A plan can protect you. A break can reveal you.',
  'options': ['Follow the plan', 'Break the pattern'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Follow the plan': {'act': 2, 'courage': 1},
                     'Break the pattern': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '◇',
  'position': 327},
 {'type': 'this_or_that',
  'title': 'One deep hour or Five quick wins?',
  'subtitle': 'Depth and momentum leave different signatures.',
  'options': ['One deep hour', 'Five quick wins'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'One deep hour': {'act': 2, 'courage': 1},
                     'Five quick wins': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '◇',
  'position': 328},
 {'type': 'this_or_that',
  'title': 'Hold the promise or Change the promise?',
  'subtitle': 'Integrity is not rigidity, but it needs evidence.',
  'options': ['Hold the promise', 'Change the promise'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Hold the promise': {'act': 2, 'courage': 1},
                     'Change the promise': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '◇',
  'position': 329},
 {'type': 'this_or_that',
  'title': 'Step away from noise or Enter the arena?',
  'subtitle': 'Sometimes the popular path is noise. Sometimes it is hiding.',
  'options': ['Step away from noise', 'Enter the arena'],
  'tags': ['expanded_feed', 'v2_copy', 'choice', 'identity'],
  'signal_weights': {'Step away from noise': {'act': 2, 'courage': 1},
                     'Enter the arena': {'reflect': 2, 'clarity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '◇',
  'position': 330},
 {'type': 'swipe',
  'title': 'I trust small proof more than big declarations.',
  'subtitle': 'Swipe right if tiny evidence beats hype for you.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '✦',
  'position': 331},
 {'type': 'swipe',
  'title': 'My next version needs fewer opinions and more reps.',
  'subtitle': 'A signal about noise, discipline, and repetition.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '✦',
  'position': 332},
 {'type': 'swipe',
  'title': 'I am tired of wanting things I do not practice.',
  'subtitle': 'Right means this sentence hits a nerve today.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '✦',
  'position': 333},
 {'type': 'swipe',
  'title': 'The popular path is loud, but not always mine.',
  'subtitle': 'A JotPop core signal.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '✦',
  'position': 334},
 {'type': 'swipe',
  'title': 'If I wait to feel ready, I will stay predictable.',
  'subtitle': 'Readiness can become a costume.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '✦',
  'position': 335},
 {'type': 'swipe',
  'title': 'I want my calendar to expose what I actually value.',
  'subtitle': 'Time is a brutal mirror.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '✦',
  'position': 336},
 {'type': 'swipe',
  'title': 'I respect myself more after a kept promise.',
  'subtitle': 'The Forge grows from this kind of evidence.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '✦',
  'position': 337},
 {'type': 'swipe',
  'title': 'I keep confusing research with movement.',
  'subtitle': 'Right if research sometimes becomes hiding.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '✦',
  'position': 338},
 {'type': 'swipe',
  'title': 'I need more honest attempts, not more perfect plans.',
  'subtitle': 'The map sharpens through attempts.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '✦',
  'position': 339},
 {'type': 'swipe',
  'title': 'My body usually knows before my story catches up.',
  'subtitle': 'A signal for energy, stress, and awareness.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '✦',
  'position': 340},
 {'type': 'swipe',
  'title': 'I want to become harder to derail.',
  'subtitle': 'Persistence without drama.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '✦',
  'position': 341},
 {'type': 'swipe',
  'title': 'I am more creative when I give myself constraints.',
  'subtitle': 'Creativity often likes a wall to push against.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '✦',
  'position': 342},
 {'type': 'swipe',
  'title': 'I avoid some tasks because they would make my future real.',
  'subtitle': 'A reflection card with teeth.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '✦',
  'position': 343},
 {'type': 'swipe',
  'title': 'I want feedback before I feel fully safe.',
  'subtitle': 'Visibility can become training.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '✦',
  'position': 344},
 {'type': 'swipe',
  'title': 'A clean environment changes my character faster than motivation.',
  'subtitle': 'Design the room, not just the mood.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '✦',
  'position': 345},
 {'type': 'swipe',
  'title': 'Some of my ambition is still hiding as entertainment.',
  'subtitle': 'Right if distraction sometimes wears a clever mask.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '✦',
  'position': 346},
 {'type': 'swipe',
  'title': 'I need a smaller promise and a sharper deadline.',
  'subtitle': 'A practical signal for the Forge.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '✦',
  'position': 347},
 {'type': 'swipe',
  'title': 'I want to be less available to generic culture.',
  'subtitle': 'More path, less noise.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '✦',
  'position': 348},
 {'type': 'swipe',
  'title': 'I learn faster when something is slightly embarrassing.',
  'subtitle': 'Embarrassment can be proof of edge.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '✦',
  'position': 349},
 {'type': 'swipe',
  'title': 'I do not need a new identity. I need repeated evidence.',
  'subtitle': 'A character is built from traces.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '✦',
  'position': 350},
 {'type': 'swipe',
  'title': 'The next hour can vote for who I am becoming.',
  'subtitle': 'Right if this frame is useful now.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '✦',
  'position': 351},
 {'type': 'swipe',
  'title': 'My best ideas need contact with reality earlier.',
  'subtitle': 'A builder card.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '✦',
  'position': 352},
 {'type': 'swipe',
  'title': 'I am not behind. I am under-practiced.',
  'subtitle': 'This changes shame into reps.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '✦',
  'position': 353},
 {'type': 'swipe',
  'title': 'I want fewer tabs open in my head.',
  'subtitle': 'A focus and clarity signal.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '✦',
  'position': 354},
 {'type': 'swipe',
  'title': 'I know the move. I am negotiating with resistance.',
  'subtitle': 'Right if the blocker is not information.',
  'options': ['Resonates', 'Not for me'],
  'tags': ['expanded_feed', 'v2_copy', 'swipe', 'pattern'],
  'signal_weights': {'Resonates': {'reflect': 2, 'identity': 1}, 'Not for me': {'non_attachment': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '✦',
  'position': 355},
 {'type': 'tap',
  'title': 'What would make today feel less generic?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['One honest rep', 'One real conversation', 'One cleaner room', 'One shipped draft'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'One honest rep': {'act': 2, 'courage': 1},
                     'One real conversation': {'reflect': 2, 'clarity': 1},
                     'One cleaner room': {'build': 2, 'creativity': 1},
                     'One shipped draft': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '◉',
  'position': 356},
 {'type': 'tap',
  'title': 'Pick the friction you are willing to face.',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Starting', 'Finishing', 'Being seen', 'Asking clearly'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Starting': {'act': 2, 'courage': 1},
                     'Finishing': {'reflect': 2, 'clarity': 1},
                     'Being seen': {'build': 2, 'creativity': 1},
                     'Asking clearly': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '◉',
  'position': 357},
 {'type': 'tap',
  'title': 'What kind of progress do you need most?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Visible output', 'Internal clarity', 'Physical energy', 'Social courage'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Visible output': {'act': 2, 'courage': 1},
                     'Internal clarity': {'reflect': 2, 'clarity': 1},
                     'Physical energy': {'build': 2, 'creativity': 1},
                     'Social courage': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '◉',
  'position': 358},
 {'type': 'tap',
  'title': 'Where is your attention leaking?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Phone loops', 'Open tabs', 'People pleasing', 'Fake planning'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Phone loops': {'act': 2, 'courage': 1},
                     'Open tabs': {'reflect': 2, 'clarity': 1},
                     'People pleasing': {'build': 2, 'creativity': 1},
                     'Fake planning': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '◉',
  'position': 359},
 {'type': 'tap',
  'title': 'Choose the next honest unit.',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['10 minutes', 'One message', 'One paragraph', 'One set'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'10 minutes': {'act': 2, 'courage': 1},
                     'One message': {'reflect': 2, 'clarity': 1},
                     'One paragraph': {'build': 2, 'creativity': 1},
                     'One set': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '◉',
  'position': 360},
 {'type': 'tap',
  'title': 'Which version of you should get more votes?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Builder', 'Athlete', 'Student', 'Connector'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Builder': {'act': 2, 'courage': 1},
                     'Athlete': {'reflect': 2, 'clarity': 1},
                     'Student': {'build': 2, 'creativity': 1},
                     'Connector': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '◉',
  'position': 361},
 {'type': 'tap',
  'title': 'What would make the Pattern Map less random?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['More action', 'More Jots', 'More focus', 'More recovery'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'More action': {'act': 2, 'courage': 1},
                     'More Jots': {'reflect': 2, 'clarity': 1},
                     'More focus': {'build': 2, 'creativity': 1},
                     'More recovery': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '◉',
  'position': 362},
 {'type': 'tap',
  'title': 'Name today’s quiet enemy.',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Comfort', 'Noise', 'Avoidance', 'Overthinking'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Comfort': {'act': 2, 'courage': 1},
                     'Noise': {'reflect': 2, 'clarity': 1},
                     'Avoidance': {'build': 2, 'creativity': 1},
                     'Overthinking': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '◉',
  'position': 363},
 {'type': 'tap',
  'title': 'What should the deck learn about you?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['What I build', 'What I avoid', 'Who I care for', 'How I recover'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'What I build': {'act': 2, 'courage': 1},
                     'What I avoid': {'reflect': 2, 'clarity': 1},
                     'Who I care for': {'build': 2, 'creativity': 1},
                     'How I recover': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '◉',
  'position': 364},
 {'type': 'tap',
  'title': 'Which signal feels strongest lately?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Restless ambition', 'Creative pressure', 'Social hunger', 'Need for silence'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Restless ambition': {'act': 2, 'courage': 1},
                     'Creative pressure': {'reflect': 2, 'clarity': 1},
                     'Social hunger': {'build': 2, 'creativity': 1},
                     'Need for silence': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '◉',
  'position': 365},
 {'type': 'tap',
  'title': 'Pick a non-popular reward.',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Peace after effort', 'Clean focus', 'A kept promise', 'A private win'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Peace after effort': {'act': 2, 'courage': 1},
                     'Clean focus': {'reflect': 2, 'clarity': 1},
                     'A kept promise': {'build': 2, 'creativity': 1},
                     'A private win': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '◉',
  'position': 366},
 {'type': 'tap',
  'title': 'What do you want to make harder?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Distraction', 'Excuses', 'Vague goals', 'Easy quitting'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Distraction': {'act': 2, 'courage': 1},
                     'Excuses': {'reflect': 2, 'clarity': 1},
                     'Vague goals': {'build': 2, 'creativity': 1},
                     'Easy quitting': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '◉',
  'position': 367},
 {'type': 'tap',
  'title': 'What do you want to make easier?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Starting', 'Training', 'Writing', 'Asking'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Starting': {'act': 2, 'courage': 1},
                     'Training': {'reflect': 2, 'clarity': 1},
                     'Writing': {'build': 2, 'creativity': 1},
                     'Asking': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '◉',
  'position': 368},
 {'type': 'tap',
  'title': 'Your next useful constraint:',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Timer', 'Public deadline', 'Smaller scope', 'Phone away'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Timer': {'act': 2, 'courage': 1},
                     'Public deadline': {'reflect': 2, 'clarity': 1},
                     'Smaller scope': {'build': 2, 'creativity': 1},
                     'Phone away': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '◉',
  'position': 369},
 {'type': 'tap',
  'title': 'Which area wants proof?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Career', 'Body', 'Relationships', 'Creative work'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Career': {'act': 2, 'courage': 1},
                     'Body': {'reflect': 2, 'clarity': 1},
                     'Relationships': {'build': 2, 'creativity': 1},
                     'Creative work': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '◉',
  'position': 370},
 {'type': 'tap',
  'title': 'What should be less dramatic?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Starting', 'Failing', 'Resting', 'Changing plans'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Starting': {'act': 2, 'courage': 1},
                     'Failing': {'reflect': 2, 'clarity': 1},
                     'Resting': {'build': 2, 'creativity': 1},
                     'Changing plans': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '◉',
  'position': 371},
 {'type': 'tap',
  'title': 'Where would a Jot help most?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Before action', 'After action', 'During resistance', 'At night'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Before action': {'act': 2, 'courage': 1},
                     'After action': {'reflect': 2, 'clarity': 1},
                     'During resistance': {'build': 2, 'creativity': 1},
                     'At night': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '◉',
  'position': 372},
 {'type': 'tap',
  'title': 'Choose the cleaner trade.',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Less noise', 'More reps', 'Less image', 'More honesty'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Less noise': {'act': 2, 'courage': 1},
                     'More reps': {'reflect': 2, 'clarity': 1},
                     'Less image': {'build': 2, 'creativity': 1},
                     'More honesty': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '◉',
  'position': 373},
 {'type': 'tap',
  'title': 'What are you actually training today?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Attention', 'Courage', 'Taste', 'Follow-through'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Attention': {'act': 2, 'courage': 1},
                     'Courage': {'reflect': 2, 'clarity': 1},
                     'Taste': {'build': 2, 'creativity': 1},
                     'Follow-through': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '◉',
  'position': 374},
 {'type': 'tap',
  'title': 'What should tomorrow inherit from today?',
  'subtitle': 'Tap the option that feels most alive now.',
  'options': ['Momentum', 'Clarity', 'Energy', 'A lesson'],
  'tags': ['expanded_feed', 'v2_copy', 'tap', 'direction'],
  'signal_weights': {'Momentum': {'act': 2, 'courage': 1},
                     'Clarity': {'reflect': 2, 'clarity': 1},
                     'Energy': {'build': 2, 'creativity': 1},
                     'A lesson': {'learn': 2, 'curiosity': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '◉',
  'position': 375},
 {'type': 'challenge',
  'title': 'Send the message you are over-editing.',
  'subtitle': 'One clean message. No performance.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '⚒',
  'position': 376},
 {'type': 'challenge',
  'title': 'Open the project and improve one visible thing.',
  'subtitle': 'Ten minutes counts.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '⚒',
  'position': 377},
 {'type': 'challenge',
  'title': 'Put the phone away for one focused block.',
  'subtitle': 'Make distraction slightly harder.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '⚒',
  'position': 378},
 {'type': 'challenge',
  'title': 'Write one sentence you have been avoiding.',
  'subtitle': 'Private proof still counts.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '⚒',
  'position': 379},
 {'type': 'challenge',
  'title': 'Do the first ugly rep.',
  'subtitle': 'The Forge does not need elegance.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '⚒',
  'position': 380},
 {'type': 'challenge',
  'title': 'Ask one specific question to one real person.',
  'subtitle': 'Connection beats imaginary feedback.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '⚒',
  'position': 381},
 {'type': 'challenge',
  'title': 'Delete one source of noise from today.',
  'subtitle': 'Less popular path, more yours.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '⚒',
  'position': 382},
 {'type': 'challenge',
  'title': 'Move your body before negotiating with your mood.',
  'subtitle': 'A physical vote for energy.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '⚒',
  'position': 383},
 {'type': 'challenge',
  'title': 'Close one open loop before opening another.',
  'subtitle': 'Completion is character evidence.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '⚒',
  'position': 384},
 {'type': 'challenge',
  'title': 'Make the task smaller until it becomes undeniable.',
  'subtitle': 'Shrink the gate.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '⚒',
  'position': 385},
 {'type': 'challenge',
  'title': 'Spend 15 minutes on the thing with future value.',
  'subtitle': 'Not urgent. Important.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '⚒',
  'position': 386},
 {'type': 'challenge',
  'title': 'Show one rough piece of work to reality.',
  'subtitle': 'Reality is the best editor.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '⚒',
  'position': 387},
 {'type': 'challenge',
  'title': 'Clean the surface where you work.',
  'subtitle': 'Environment is hidden discipline.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '⚒',
  'position': 388},
 {'type': 'challenge',
  'title': 'Write the promise you actually intend to keep.',
  'subtitle': 'No heroic fiction.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '⚒',
  'position': 389},
 {'type': 'challenge',
  'title': 'Stop one scroll earlier than usual.',
  'subtitle': 'A tiny rebellion against default culture.',
  'options': ['Accept challenge', 'Not today'],
  'tags': ['expanded_feed', 'v2_copy', 'challenge', 'promise_seed'],
  'signal_weights': {'Accept challenge': {'act': 2, 'follow_through': 1}, 'Not today': {'resistance': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '⚒',
  'position': 390},
 {'type': 'micro_jot',
  'title': 'What did you almost do, but avoided?',
  'subtitle': 'One sentence. No decoration.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '✍',
  'position': 391},
 {'type': 'micro_jot',
  'title': 'What felt more yours than popular today?',
  'subtitle': 'Give the deck a personal trace.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '✍',
  'position': 392},
 {'type': 'micro_jot',
  'title': 'What are you pretending is complicated?',
  'subtitle': 'Write the simple version.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '✍',
  'position': 393},
 {'type': 'micro_jot',
  'title': 'Which promise would actually change tomorrow?',
  'subtitle': 'Name it before it becomes vague.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'gold',
  'icon': '✍',
  'position': 394},
 {'type': 'micro_jot',
  'title': 'What made you feel alive for five seconds?',
  'subtitle': 'Small signals count.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'ember',
  'icon': '✍',
  'position': 395},
 {'type': 'micro_jot',
  'title': 'What are you protecting by delaying?',
  'subtitle': 'One sentence off the popular path.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'deepblue',
  'icon': '✍',
  'position': 396},
 {'type': 'micro_jot',
  'title': 'What should JotPop stop assuming about you?',
  'subtitle': 'Personalization starts here.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'pulse',
  'icon': '✍',
  'position': 397},
 {'type': 'micro_jot',
  'title': 'What did your resistance say today?',
  'subtitle': 'Quote it if you can.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'aether',
  'icon': '✍',
  'position': 398},
 {'type': 'micro_jot',
  'title': 'What kind of person did you practice being?',
  'subtitle': 'Make the invisible visible.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'signal',
  'icon': '✍',
  'position': 399},
 {'type': 'micro_jot',
  'title': 'What would make the next card more personal?',
  'subtitle': 'Give the deck a clue.',
  'options': [],
  'tags': ['expanded_feed', 'v2_copy', 'micro_jot', 'personalization'],
  'signal_weights': {'submitted': {'reflect': 2, 'jot': 2, 'identity': 1}},
  'is_onboarding': False,
  'visual_theme': 'void',
  'icon': '✍',
  'position': 400}]

INITIAL_CARDS = INITIAL_CARDS + VARIED_FEED_CARDS
