INITIAL_PROMISE_TEMPLATES = [
    {
        "title": "Work 25 minutes on one meaningful project",
        "description": "Pick one project that matters and give it one focused block. No perfect plan required.",
        "difficulty": "Hard",
        "forge_points": 3,
        "tags": ["build", "focus", "career", "project"],
        "suggestion_weight": 100,
        "is_active": True,
    },
    {
        "title": "Move your body for 20 minutes",
        "description": "Walk, stretch, train, or do simple mobility. The goal is to show your body you are present.",
        "difficulty": "Medium",
        "forge_points": 2,
        "tags": ["body", "energy", "fitness"],
        "suggestion_weight": 95,
        "is_active": True,
    },
    {
        "title": "Read or study for 10 minutes",
        "description": "Open one useful source and absorb something that could make tomorrow easier.",
        "difficulty": "Easy",
        "forge_points": 1,
        "tags": ["learning", "clarity", "knowledge"],
        "suggestion_weight": 90,
        "is_active": True,
    },
    {
        "title": "Write one honest Jot about what matters today",
        "description": "Capture one short thought about what feels important, avoided, or alive today.",
        "difficulty": "Easy",
        "forge_points": 1,
        "tags": ["reflection", "jot", "awareness"],
        "suggestion_weight": 88,
        "is_active": True,
    },
    {
        "title": "Send one useful message to someone",
        "description": "Help, encourage, ask, thank, or reconnect. Make one relationship signal real.",
        "difficulty": "Medium",
        "forge_points": 2,
        "tags": ["social", "relationships", "network"],
        "suggestion_weight": 84,
        "is_active": True,
    },
    {
        "title": "Clean or reset one small area",
        "description": "Desk, bag, room corner, inbox, browser tabs. Reset one environment that affects your mind.",
        "difficulty": "Easy",
        "forge_points": 1,
        "tags": ["environment", "order", "clarity"],
        "suggestion_weight": 80,
        "is_active": True,
    },
    {
        "title": "Practice one skill for 20 minutes",
        "description": "Choose one skill you want to become known for and repeat the basics deliberately.",
        "difficulty": "Medium",
        "forge_points": 2,
        "tags": ["skill", "mastery", "practice"],
        "suggestion_weight": 78,
        "is_active": True,
    },
    {
        "title": "Make one decision you have been postponing",
        "description": "Pick the next clear move. Small decisions count if they reduce mental fog.",
        "difficulty": "Hard",
        "forge_points": 3,
        "tags": ["decision", "courage", "clarity"],
        "suggestion_weight": 74,
        "is_active": True,
    },
    {
        "title": "Spend 15 minutes without passive scrolling",
        "description": "Put the phone away and let your attention return to something intentional.",
        "difficulty": "Medium",
        "forge_points": 2,
        "tags": ["discipline", "attention", "energy"],
        "suggestion_weight": 70,
        "is_active": True,
    },
    {
        "title": "Prepare one thing that makes tomorrow easier",
        "description": "Lay out clothes, plan a first task, prep food, organize notes, or remove one future obstacle.",
        "difficulty": "Easy",
        "forge_points": 1,
        "tags": ["planning", "future", "support"],
        "suggestion_weight": 66,
        "is_active": True,
    },
    {
        "title": "Do one uncomfortable but useful thing",
        "description": "A call, a question, a first draft, a repair, an ask. Choose something small but real.",
        "difficulty": "Hard",
        "forge_points": 3,
        "tags": ["courage", "growth", "action"],
        "suggestion_weight": 62,
        "is_active": True,
    },
    {
        "title": "Review your day for 5 minutes before sleep",
        "description": "Ask: what did I protect, avoid, build, or learn today? Keep it short.",
        "difficulty": "Easy",
        "forge_points": 1,
        "tags": ["reflection", "evening", "awareness"],
        "suggestion_weight": 58,
        "is_active": True,
    },
]
